# Generated by Django 2.2.5 on 2020-09-02 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pants',
        ),
        migrations.RemoveField(
            model_name='user',
            name='shoes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tops',
        ),
    ]
