# Generated by Django 2.2.5 on 2020-10-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertops',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topsimage',
            name='top',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tops.Tops'),
        ),
    ]
