# Generated by Django 2.2.5 on 2020-09-02 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(max_length=250)),
                ('img', models.ImageField(upload_to='userTop')),
                ('meta_top', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarThings', to='tops.Tops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
