# Generated by Django 2.2.5 on 2020-09-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0002_usertops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertops',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userTops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usertops',
            name='vector',
            field=models.BinaryField(max_length=250, null=True),
        ),
    ]
