# Generated by Django 2.2.5 on 2020-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tops', '0002_auto_20201025_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertops',
            name='nickname',
            field=models.CharField(default='top_<django.db.models.fields.AutoField>', max_length=50),
        ),
        migrations.AlterField(
            model_name='usertops',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
