# Generated by Django 2.2.5 on 2020-10-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('item_url', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('shop', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PantsImage',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='pants')),
                ('vector', models.BinaryField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserPants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(max_length=250, null=True)),
                ('img', models.ImageField(upload_to='userPants')),
                ('jjim', models.BooleanField(default=False)),
                ('meta_pants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarThings', to='pants.Pants')),
            ],
        ),
    ]
