# Generated by Django 2.2.5 on 2020-09-01 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('item_url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PantsImage',
            fields=[
                ('_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('img_url', models.CharField(max_length=150)),
                ('img_dir', models.CharField(max_length=150)),
                ('vector', models.BinaryField(max_length=250)),
                ('pants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pants.Pants')),
            ],
        ),
    ]
