# Generated by Django 2.2.5 on 2020-07-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=15)),
                ('brand', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=100)),
                ('item_url', models.CharField(max_length=150)),
            ],
        ),
    ]
