# Generated by Django 2.2.5 on 2020-09-27 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.BinaryField(max_length=250, null=True)),
                ('img', models.ImageField(upload_to='userPants')),
                ('meta_pants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarThings', to='pants.Pants')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userPants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
