# Generated by Django 2.2.5 on 2020-10-25 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userShoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoesimage',
            name='shoes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shoes.Shoes'),
        ),
    ]
