# Generated by Django 2.2.5 on 2020-10-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20201025_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershoes',
            name='nickname',
            field=models.CharField(default='shoes', max_length=50),
        ),
        migrations.AlterField(
            model_name='usershoes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
