# Generated by Django 2.2.5 on 2020-10-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cody',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='cody/cody')),
                ('jjim', models.BooleanField(default=False)),
                ('cody_top_img', models.ImageField(upload_to='cody/top')),
                ('cody_pants_img', models.ImageField(upload_to='cody/pants')),
                ('cody_shoes_img', models.ImageField(upload_to='cody/shoes')),
            ],
        ),
    ]
