# Generated by Django 2.2.5 on 2020-10-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cody',
            name='form',
            field=models.IntegerField(default=0),
        ),
    ]
